version: "3.9"
services:
  postgres:
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Khmlxk12
      - POSTGRES_DB=dokbetav0
  
  server:
    depends_on: 
      - postgres
    build:
      context: ./Server
      dockerfile: Dockerfile
    environment:
     - DB_SCHEMA=dokbetav0
     - DB_USER=postgres
     - DB_PASSWORD=Khmlxk12
     - DB_HOST=postgres
    ports:
      - "5000:5000"
      
    

  react:
    build:
      context: ./dokbetav
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
    depends_on: 
        - server
    environment: 
      - SERVER=server

